### ISSUE TITLE
VS17 Support

### ISSUE THREAD

**Issue by mstein11** [ceztko/SolutionConfigurationName#2]
Is there a plan to make this extension available to VS17?

**Comment by ceztko** [comment]
Working on this right now.

**Comment by ceztko** [comment]
API for accessing project internal settings is public now[1], which is positive, but changed a bit so I've to learn it.

[1] https://github.com/Microsoft/VSProjectSystem

**Comment by ceztko** [comment]
Done. No functional change was needed to support the new API. I've tested it with my usual simple test case (C++ only) and it works. No idea if the concept still works with C# projects: it used to work but I'm not using the extension actively.

https://marketplace.visualstudio.com/items?itemName=ceztko.SolutionConfigurationName
